### ISSUE TITLE
Feature Request: Add POST method to upload weather data to Parser

### ISSUE THREAD

**Issue by shbatm** [bachya/regenmaschine#102]
**Is your feature request related to a problem? Please describe.**
I would like to be able to use this module and a new service in the Home Assistant integration to push weather from my local weather station to the RainMachine

**Describe the solution you'd like**
Implement a POST method for this: https://rainmachine.docs.apiary.io/#reference/weather-services/parserdata/post so you can send JSON to the module and use the existing infrastructure / authentication to send it.

**Describe alternatives you've considered**
Using separate REST commands to authenticate and send it using NodeRED.

**Additional context**
This was added in API 4.6 here: https://rainmachine.docs.apiary.io/#reference/weather-services/parserdata/post

**Comment by shbatm** [comment]
Added a draft PR while testing. I will add module tests when I get a chance. Have an intiial service working in Home Assistant, will share when ready.

**Comment by shbatm** [comment]
Home Assistant Service for testing: works fine but needs some code cleanup. Will get back to it when I can:

https://github.com/shbatm/home-assistant/commit/736fd6a818093acb7deb99c1de1c746c1299dca1

**Comment by bachya** [comment]
Thanks for taking a stab at this! Always appreciate partnership. Let me know when you're ready for review.
