### ISSUE TITLE
Flow sensors not working in home assistant

### ISSUE THREAD

**Issue by garbled1** [bachya/regenmaschine#105]
**Describe the bug**
This is the same as #96 , flow sensors are not working in home assistant.  I am however, attaching what you requested in that issue, as logs.

**To Reproduce**

Home assistant, expect flow sensors to exist, as they used to in older version

**Expected behavior**
Home assistant, expect flow sensors to exist, as they used to in older version

**Screenshots**

**Desktop (please complete the following information):**
Home assistant 2021.10.2

**Additional context**

You requested specific data from the original requestor in #96  attaching here.

```json
{
  "system": {
    "httpEnabled": true,
    "rainSensorSnoozeDuration": 0,
    "selfTest": false,
    "uiUnitsMetric": false,
    "programZonesShowInactive": false,
    "localValveCount": 17,
    "programSingleSchedule": false,
    "standaloneMode": false,
    "masterValveAfter": 0,
    "touchAdvanced": false,
    "useFlowSensor": true,
    "useSoftwareRainSensor": false,
    "defaultZoneWateringDuration": 300,
    "maxLEDBrightness": 40,
    "simulatorHistorySize": 0,
    "vibration": false,
    "useCorrectionForPast": true,
    "spk5LockBrightness": 10,
    "masterValveBefore": 0,
    "touchProgramToRun": null,
    "useRainSensor": false,
    "wizardHasRun": true,
    "waterLogHistorySize": 365,
    "netName": "Maia",
    "automaticUpdates": true,
    "flowSensorLeakClicks": 610835,
    "softwareRainSensorMinQPF": 5,
    "useBonjourService": true,
    "hardwareVersion": 5,
    "touchLongPressTimeout": 3,
    "showRestrictionsOnLed": false,
    "parserDataSizeInDays": 6,
    "programListShowInactive": true,
    "parserHistorySize": 365,
    "flowSensorStartIndex": 1873651,
    "allowAlexaDiscovery": false,
    "maxZoneDuration": 86400,
    "minLEDBrightness": 0,
    "minWateringDurationThreshold": 30,
    "simulatorSkipRunSoonDynamic": 43200,
    "touchSleepTimeout": 120,
    "lastLeakDetected": 1632689220,
    "touchAuthAPSeconds": 60,
    "carryOverInRestriction": false,
    "useCommandLineArguments": false,
    "flowSensorClicksPerCubicMeter": 264.2,
    "databasePath": "/rainmachine-app/DB/Default",
    "touchCyclePrograms": true,
    "dedicatedMasterValve": true,
    "flowSensorWateringClicks": 458288,
    "zoneListShowInactive": true,
    "rainSensorRainStart": null,
    "zoneDuration": [
      300,
      300,
      300,
      300,
      300,
      300,
      300,
      300,
      300,
      300,
      300,
      300,
      300,
      300,
      300,
      300,
      300
    ],
    "spk5TouchSleepTimeoutNight": 0,
    "rainSensorIsNormallyClosed": true,
    "spk5LCDBrightness": 50,
    "useMasterValve": false,
    "runParsersBeforePrograms": true,
    "spk5LEDBrightness": 2,
    "maxWateringCoef": 1.5,
    "mixerHistorySize": 365
  },
  "location": {
    "elevation": 403.156524658,
    "doyDownloaded": true,
    "zip": null,
    "windSensitivity": 0.6,
    "krs": 0.16,
    "stationID": 428,
    "stationSource": "station",
    "et0Average": 8.173,
    "latitude": 33.700163,
    "state": "Default",
    "stationName": "YOUNGTOWN",
    "wsDays": 2,
    "stationDownloaded": true,
    "address": "Default",
    "rainSensitivity": 0.25,
    "timezone": "America/Phoenix",
    "longitude": -112.2286683,
    "name": "X"
  }
}
```

What I see in homeassistant, is that flow_sensor_clicks is showing as "264.2" and not "458288".  I do see a flow_sensor_watering_clicks_2, I'm going to try enabling that to see if that has the proper values...

**Comment by bachya** [comment]
Alright, based on the Home Assistant RainMachine code, here's what *should* be happening:

1. The integration creates four flow sensor-related entities (note that _all_ of these entities are disabled by default since most people don't have a flow sensor with their RainMachine):
    * `Flow Sensor Clicks` (measured in clicks/meters^3)
    * `Flow Sensor Consumed Liters`
    * `Flow Sensor Start Index`
    * `Flow Sensor Clicks` (measured in clicks)
2. Based on your data, you should see these values:
    * `Flow Sensor Clicks` (measured in clicks/meters^3): 264.2
    * `Flow Sensor Consumed Liters`: 1734625.28 (`(458288 * 1000) / 264.2`)
    * `Flow Sensor Start Index`: 1873651
    * `Flow Sensor Clicks` (measured in clicks): 458288

My questions:

* Have you confirmed that all of these sensors exist in your integration?
* Are these sensors all enabled?
* Do the sensors have the same or different values vs. what I've posted here?

**Comment by bachya** [comment]
Got it! Let me know if/when you have data on that last sensor and we'll go from there.

The fact that the entity ID has a `_2` after it makes me think that I need to do better at distinguishing. After you report back, I'll think about what to do there.

**Comment by garbled1** [comment]
OK, got lucky and a sprinkler just went off.

![image](https://user-images.githubusercontent.com/6556271/137212186-60a7dc1c-efeb-40e2-a705-c31ff4294a11.png)
