### ISSUE TITLE
Zone Active differences in hardware.

### ISSUE THREAD

**Issue by tfitts** [bachya/regenmaschine#11]
I guess there are a few other differences in API responses between generations of hardware.  After updating to this I was able to connect to my RainMachine and in HA the Program shows up but none of the zones do.  I saw that you made a change that turns off the option to hide inactive zones and make it always hide them.  Turns out gen 1 doesn't include active state in the zones command, it includes it in a separate properties command.

Here is the response from the zone command:

{ "zones":
[{ "uid":1,"name":"Front Yard South","state":0,"userDuration":0,"machineDuration":0,"remaining":0,"cycle":0,"noOfCycles":0,"restriction":false,"type":2,"master":false,"waterSense":false},
{ "uid":2,"name":"Front Yard Center","state":0,"userDuration":0,"machineDuration":0,"remaining":0,"cycle":0,"noOfCycles":0,"restriction":false,"type":2,"master":false,"waterSense":false},
{ "uid":3,"name":"Front Yard North","state":0,"userDuration":0,"machineDuration":0,"remaining":0,"cycle":0,"noOfCycles":0,"restriction":false,"type":2,"master":false,"waterSense":false},
{ "uid":4,"name":"Back Yard North","state":0,"userDuration":0,"machineDuration":0,"remaining":0,"cycle":0,"noOfCycles":0,"restriction":false,"type":2,"master":false,"waterSense":false},
{ "uid":5,"name":"Back Yard Center","state":0,"userDuration":0,"machineDuration":0,"remaining":0,"cycle":0,"noOfCycles":0,"restriction":false,"type":2,"master":false,"waterSense":false},
{ "uid":6,"name":"Back Yard South","state":0,"userDuration":0,"machineDuration":0,"remaining":0,"cycle":0,"noOfCycles":0,"restriction":false,"type":2,"master":false,"waterSense":false},
{ "uid":7,"name":"Drip Line","state":0,"userDuration":0,"machineDuration":0,"remaining":0,"cycle":0,"noOfCycles":0,"restriction":false,"type":7,"master":false,"waterSense":false},
{ "uid":8,"name":"Zone 8","state":0,"userDuration":0,"machineDuration":0,"remaining":0,"cycle":0,"noOfCycles":0,"restriction":false,"type":1,"master":false,"waterSense":false},
{ "uid":9,"name":"Zone 9","state":0,"userDuration":0,"machineDuration":0,"remaining":0,"cycle":0,"noOfCycles":0,"restriction":false,"type":8,"master":false,"waterSense":false},
{ "uid":10,"name":"Zone 10","state":0,"userDuration":0,"machineDuration":0,"remaining":0,"cycle":0,"noOfCycles":0,"restriction":false,"type":8,"master":false,"waterSense":false},
{ "uid":11,"name":"Zone 11","state":0,"userDuration":0,"machineDuration":0,"remaining":0,"cycle":0,"noOfCycles":0,"restriction":false,"type":8,"master":false,"waterSense":false},
{ "uid":12,"name":"Zone 12","state":0,"userDuration":0,"machineDuration":0,"remaining":0,"cycle":0,"noOfCycles":0,"restriction":false,"type":8,"master":false,"waterSense":false}]}

And from the properties command:

{ "zones" : [ { "uid":1,"name":"Front Yard South","valveid":1,"ETcoef":0,"active":true,"type":2,"internet":true,"savings":0,"slope":0,"sun":0,"soil":0,"group_id":0,"history":true,"master":false,"before":-1,"after":-1,"waterSense":{ "maxAllowedDepletion":0,"precipitationRate":0,"appEfficiency":0,"allowedSurfaceAcc":0,"rootDepth":0,"isTallPlant":0,"soilIntakeRate":0,"detailedMonthsKc":[1,1,1,1,1,1,1,1,1,1,1,1],"permWilting":0,"fieldCapacity":0}}
,{ "uid":2,"name":"Front Yard Center","valveid":2,"ETcoef":0,"active":true,"type":2,"internet":true,"savings":0,"slope":0,"sun":0,"soil":0,"group_id":0,"history":true,"master":false,"before":-1,"after":-1,"waterSense":{ "maxAllowedDepletion":0,"precipitationRate":0,"appEfficiency":0,"allowedSurfaceAcc":0,"rootDepth":0,"isTallPlant":0,"soilIntakeRate":0,"detailedMonthsKc":[1,1,1,1,1,1,1,1,1,1,1,1],"permWilting":0,"fieldCapacity":0}}
,{ "uid":3,"name":"Front Yard North","valveid":3,"ETcoef":0,"active":true,"type":2,"internet":true,"savings":0,"slope":0,"sun":0,"soil":0,"group_id":0,"history":true,"master":false,"before":-1,"after":-1,"waterSense":{ "maxAllowedDepletion":0,"precipitationRate":0,"appEfficiency":0,"allowedSurfaceAcc":0,"rootDepth":0,"isTallPlant":0,"soilIntakeRate":0,"detailedMonthsKc":[1,1,1,1,1,1,1,1,1,1,1,1],"permWilting":0,"fieldCapacity":0}}
,{ "uid":4,"name":"Back Yard North","valveid":4,"ETcoef":0,"active":true,"type":2,"internet":true,"savings":0,"slope":0,"sun":0,"soil":0,"group_id":0,"history":true,"master":false,"before":-1,"after":-1,"waterSense":{ "maxAllowedDepletion":0,"precipitationRate":0,"appEfficiency":0,"allowedSurfaceAcc":0,"rootDepth":0,"isTallPlant":0,"soilIntakeRate":0,"detailedMonthsKc":[1,1,1,1,1,1,1,1,1,1,1,1],"permWilting":0,"fieldCapacity":0}}
,{ "uid":5,"name":"Back Yard Center","valveid":5,"ETcoef":0,"active":true,"type":2,"internet":true,"savings":0,"slope":0,"sun":0,"soil":0,"group_id":0,"history":true,"master":false,"before":-1,"after":-1,"waterSense":{ "maxAllowedDepletion":0,"precipitationRate":0,"appEfficiency":0,"allowedSurfaceAcc":0,"rootDepth":0,"isTallPlant":0,"soilIntakeRate":0,"detailedMonthsKc":[1,1,1,1,1,1,1,1,1,1,1,1],"permWilting":0,"fieldCapacity":0}}
,{ "uid":6,"name":"Back Yard South","valveid":6,"ETcoef":0,"active":true,"type":2,"internet":true,"savings":0,"slope":0,"sun":0,"soil":0,"group_id":0,"history":true,"master":false,"before":-1,"after":-1,"waterSense":{ "maxAllowedDepletion":0,"precipitationRate":0,"appEfficiency":0,"allowedSurfaceAcc":0,"rootDepth":0,"isTallPlant":0,"soilIntakeRate":0,"detailedMonthsKc":[1,1,1,1,1,1,1,1,1,1,1,1],"permWilting":0,"fieldCapacity":0}}
,{ "uid":7,"name":"Drip Line","valveid":7,"ETcoef":0,"active":true,"type":7,"internet":true,"savings":0,"slope":0,"sun":0,"soil":0,"group_id":0,"history":true,"master":false,"before":-1,"after":-1,"waterSense":{ "maxAllowedDepletion":0,"precipitationRate":0,"appEfficiency":0,"allowedSurfaceAcc":0,"rootDepth":0,"isTallPlant":0,"soilIntakeRate":0,"detailedMonthsKc":[1,1,1,1,1,1,1,1,1,1,1,1],"permWilting":0,"fieldCapacity":0}}
,{ "uid":8,"name":"Zone 8","valveid":8,"ETcoef":0,"active":true,"type":1,"internet":true,"savings":0,"slope":0,"sun":0,"soil":0,"group_id":0,"history":true,"master":false,"before":-1,"after":-1,"waterSense":{ "maxAllowedDepletion":0,"precipitationRate":0,"appEfficiency":0,"allowedSurfaceAcc":0,"rootDepth":0,"isTallPlant":0,"soilIntakeRate":0,"detailedMonthsKc":[1,1,1,1,1,1,1,1,1,1,1,1],"permWilting":0,"fieldCapacity":0}}
,{ "uid":9,"name":"Zone 9","valveid":9,"ETcoef":0,"active":false,"type":8,"internet":true,"savings":0,"slope":0,"sun":0,"soil":0,"group_id":0,"history":true,"master":false,"before":-1,"after":-1,"waterSense":{ "maxAllowedDepletion":0,"precipitationRate":0,"appEfficiency":0,"allowedSurfaceAcc":0,"rootDepth":0,"isTallPlant":0,"soilIntakeRate":0,"detailedMonthsKc":[1,1,1,1,1,1,1,1,1,1,1,1],"permWilting":0,"fieldCapacity":0}}
,{ "uid":10,"name":"Zone 10","valveid":10,"ETcoef":0,"active":false,"type":8,"internet":true,"savings":0,"slope":0,"sun":0,"soil":0,"group_id":0,"history":true,"master":false,"before":-1,"after":-1,"waterSense":{ "maxAllowedDepletion":0,"precipitationRate":0,"appEfficiency":0,"allowedSurfaceAcc":0,"rootDepth":0,"isTallPlant":0,"soilIntakeRate":0,"detailedMonthsKc":[1,1,1,1,1,1,1,1,1,1,1,1],"permWilting":0,"fieldCapacity":0}}
,{ "uid":11,"name":"Zone 11","valveid":11,"ETcoef":0,"active":false,"type":8,"internet":true,"savings":0,"slope":0,"sun":0,"soil":0,"group_id":0,"history":true,"master":false,"before":-1,"after":-1,"waterSense":{ "maxAllowedDepletion":0,"precipitationRate":0,"appEfficiency":0,"allowedSurfaceAcc":0,"rootDepth":0,"isTallPlant":0,"soilIntakeRate":0,"detailedMonthsKc":[1,1,1,1,1,1,1,1,1,1,1,1],"permWilting":0,"fieldCapacity":0}}
,{ "uid":12,"name":"Zone 12","valveid":12,"ETcoef":0,"active":false,"type":8,"internet":true,"savings":0,"slope":0,"sun":0,"soil":0,"group_id":0,"history":true,"master":false,"before":-1,"after":-1,"waterSense":{ "maxAllowedDepletion":0,"precipitationRate":0,"appEfficiency":0,"allowedSurfaceAcc":0,"rootDepth":0,"isTallPlant":0,"soilIntakeRate":0,"detailedMonthsKc":[1,1,1,1,1,1,1,1,1,1,1,1],"permWilting":0,"fieldCapacity":0}}
] }

So active is in the properties instead of zones.  Not sure if we can pull the properties command on the first request and merge in the active attribute or make hiding them optional again in the HA component.  I like the autohide option other than it leaves my system with all zones hidden.

Thanks again for your work on this.  I don't see too many other changes being required to support all hardware.

**Comment by bachya** [comment]
@tfitts: Got it. I think the best route forward would be for to submit a PR that accomplishes what you need; I'll review it with you and can merge it in. That work?

**Comment by tfitts** [comment]
Yeah, I will try to work on it this week sometime. Thanks!

**Comment by bachya** [comment]
Closed due to inactivity.
