### ISSUE TITLE
Support for multi-day snooze?

### ISSUE THREAD

**Issue by mrand** [bachya/regenmaschine#114]
**Is your feature request related to a problem? Please describe.**

My RainMachine appears to support a snooze function for multiple days on its webpage.
I see that there is a Home Assistant service call to "pause", and digging into the source, it seems to be limited to 24 hours (although the HA documentation page doesn't state this).

**Describe the solution you'd like**
A way to snooze for X number of days (where X is at least 8, preferably much larger).

**Comment by bachya** [comment]
To my knowledge, there isn't anything in this codebase or the Home Assistant codebase that limits the `rainmachine.pause_watering` service to 24 hours – can you share where you saw this?

**Comment by mrand** [comment]
I haven't actually tried it, so I don't know if it's enforced.   This is what I was referring to:

https://github.com/home-assistant/core/blob/92b48cca7e51a8f42f0a3f73bc94c9a94ad84f2f/homeassistant/components/rainmachine/services.yaml#L48

The reason I haven't tried it is because it isn't clear to me what a "Device ID" is (apparently different than the entity name, [according to the wording in the HA documentation](https://www.home-assistant.io/integrations/rainmachine/#services), but it doesn't provide any guidance).  I'd be happy to help improve that documentation page if you could explain it.   Thanks!

**Comment by bachya** [comment]
Got it; thanks!

Interestingly, it seems that my RainMachine returns an `HTTP 401` when I attempt to pause watering above a certain threshold – no clue what that threshold is, sadly (and [the API docs](https://rainmachine.docs.apiary.io) don't give me any hints)... I'll try to (haphazardly) figure out that upper limit and update.

RE: snoozing, I see the same page on mine (under `Settings -> Snooze`):

<img width="604" alt="CleanShot 2022-01-16 at 15 59 00@2x" src="https://user-images.githubusercontent.com/47216/149681660-9476a566-3a88-479b-b5ea-7d8e91a2ecd7.png">

It looks like triggering a snooze makes use of the [`restriction` module](https://github.com/bachya/regenmaschine/blob/dev/regenmaschine/restriction.py) – specifically, a method I haven't fleshed out yet. Should be easy to add!
