### ISSUE TITLE
Unhandled exception: `ModuleNotFoundError: No module named 'typing_extensions'`

### ISSUE THREAD

**Issue by geoffsharris** [bachya/regenmaschine#156]
Attempted to install, but had to manually add typing and typing_extensions through pip3. I think these should be additional dependencies in the setup.py.

**Comment by bachya** [comment]
Please specify more info:

1. What are you trying to install? `regenmaschine` (from PyPI), or setting up the dev environment from this repo?
2. What errors do you see that indicate you need to add those other libraries manually?

**Comment by geoffsharris** [comment]
Did 
pip3 install Regenmaschine to system 3.10.2 python on M1 Mac

Used library in a python based plugin for a home automation server.
I get an error that typing_extensions is missing and if it install separately, the library works just fine.

**Comment by bachya** [comment]
Ah, okay – I see where the issue is. Thanks!
