### ISSUE TITLE
watering/zone API command appears missing

### ISSUE THREAD

**Issue by geoffsharris** [bachya/regenmaschine#158]
in an older version of the "watering" code there was the ability to get the active program and zone:

def zone(self):
        """Return the queue of active watering activities."""
        return self._request("get", "watering/zone")

def program(self):
        """Return the queue of active watering activities."""
        return self._request("get", "watering/program")

It appears that this new library has in the "program" code the ability to access "watering/program" to get the active program, but is missing the "watering/zone" code in either program, watering or zone

**Comment by geoffsharris** [comment]
Awesome - Thank you!

**Comment by geoffsharris** [comment]
Can you do a release with this updated version incorporating #159? I've built a python based plugin for a home automation package that uses your library and includes this API link. I've tested your code and works great. Just want to make sure that people that install the library have this included before I release the plugin.

**Comment by bachya** [comment]
@geoffsharris [2022.11.2](https://github.com/bachya/regenmaschine/releases/tag/2022.11.2) released!
