### ISSUE TITLE
Export watering history for 7 days

### ISSUE THREAD

**Issue by mvawter** [bachya/regenmaschine#260]
Is there a python code to export each zone watering history, date, start time, end time? 
currently, I use the Rainmachine app, but it is always multiple steps. 
best, Mark

**Comment by bachya** [comment]
Have you tried the [`controller.watering.log` endpoint](https://github.com/bachya/regenmaschine/blob/fc9ae7aca05b37a8847d5abf7cbffa5745a438de/regenmaschine/endpoints/watering.py#L16-L21)?

If you need example usage, check out both the README and [the example](https://github.com/bachya/regenmaschine/blob/dev/examples/test_api.py).

**Comment by mvawter** [comment]
Thanks Aaron , your program looks truly remarkable. I am new to your git hub site and to python. it may take me a few iterations to actually set up the python environment and successfully download the watering history data from my RainMachine.

By the way, I’m using a flow meter that I hooked up to a data logger called sensaphone web 600. I have an excel macro that integrates the water history data with the flow meter data to produce some interesting charts of water flow rates at any given day and cycle.



Best wishes, Marquis P Vawter
________________________________

**Comment by bachya** [comment]
Let me know how things go, and feel free to post back here with questions!

**Comment by mvawter** [comment]
Hi Aaron, in this setting up of the client, I am not able to contact my machine. I have to use a static IP to reach my rainmachine.
I have tried this code below, where I put XXXXX to disguise my  password. Can you suggest changes as I don’t think I am reaching my rainmachine. I know it is on, as I can reach it by the iOS phone app.
I can also post a scaled back version of this question on github.
Thanks, Mark

import asyncio

from aiohttp import ClientSession

from regenmaschine import Client


async def main() -> None:
    """Run!"""
    async with ClientSession() as session:
        client = Client(session=session)

        await client.load_local("166.130.6.171", "XXXXXXXX", port=8080, use_ssl=True)

        controllers = client.controllers
        # >>> {'d0:37:45:da:d6:12': <LocalController>}

**Comment by bachya** [comment]
What errors are you receiving?

**Comment by mvawter** [comment]
I ran this code with the guest support PIN

from aiohttp import ClientSession

from regenmaschine import Client


async def main() -> None:
    """Run!"""
    async with ClientSession() as session:
        client = Client(session=session)

        await client.load_local("166.130.6.171", "360530", port=8080, use_ssl=True)

        controllers = client.controllers
               {'d0:37:45:da:d6:12'}


asyncio.run(main())


The errors are:
c:\Water History Report\regenmaschine>python load-local2.py
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000026E72537010>
Traceback (most recent call last):
  File "C:\Users\mvawter\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Users\mvawter\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\mvawter\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 745, in call_soon
    self._check_closed()
  File "C:\Users\mvawter\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed

**Comment by mvawter** [comment]
Here is my RainMachine direct network access screenshot!

Best wishes, Marquis P Vawter
________________________________
From: Vawter, Marquis
Sent: Tuesday, May 2, 2023 2:28:03 PM
To: bachya/regenmaschine ***@***.***>
Subject: RE: [bachya/regenmaschine] Export watering history for 7 days (Issue #260)


I ran this code with the guest support PIN



from aiohttp import ClientSession



from regenmaschine import Client





async def main() -> None:

    """Run!"""

    async with ClientSession() as session:

        client = Client(session=session)



        await client.load_local("166.130.6.171", "360530", port=8080, use_ssl=True)



        controllers = client.controllers

               {'d0:37:45:da:d6:12'}





asyncio.run(main())





The errors are:

c:\Water History Report\regenmaschine>python load-local2.py

Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000026E72537010>

Traceback (most recent call last):

  File "C:\Users\mvawter\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 116, in __del__

    self.close()

  File "C:\Users\mvawter\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 108, in close

    self._loop.call_soon(self._call_connection_lost, None)

  File "C:\Users\mvawter\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 745, in call_soon

    self._check_closed()

  File "C:\Users\mvawter\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 510, in _check_closed

    raise RuntimeError('Event loop is closed')

RuntimeError: Event loop is closed

**Comment by bachya** [comment]
Does your example work when you use your RainMachine password (instead of a guest PIN)?

**Comment by mvawter** [comment]
No I tried that.

Best wishes, Marquis P Vawter
________________________________

**Comment by bachya** [comment]
I notice you're on Windows—a quick Google yielded [this StackOverflow post](https://stackoverflow.com/questions/45600579/asyncio-event-loop-is-closed-when-getting-loop). See the first answer:

> On Windows seems to be a problem with EventLoopPolicy, use this snippet to work around it:
> 
> ```python
> asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())
> asyncio.run(main())
> ```

Give that a try?

**Comment by mvawter** [comment]
Traceback (most recent call last):
  File "c:\Water History Report\regenmaschine\load-local2.py", line 8, in <module>
    asyncio.run(main())
NameError: name 'main' is not defined. Did you mean: 'min'?


I ran  code and got the error above:

from aiohttp import ClientSession

from regenmaschine import Client

asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())
asyncio.run(main())


async def main() -> None:
    """Run!"""
    async with ClientSession() as session:
        client = Client(session=session)

        await client.load_local("166.130.6.171", "360530", port=8080, use_ssl=True)

        controllers = client.controllers
               {'d0:37:45:da:d6:12'}

**Comment by mvawter** [comment]
Okay, success in running your example / test_api.py with the guest PIN. I didn’t add my MAC. I didn’t have the asyncio.set code below, and there was exhaustive output as follows, ending with loop policy error.
I will try to fix it with the code your previously sent.
c:\Water History Report\regenmaschine>python example.py
INFO:__main__:CLIENT INFORMATION
INFO:__main__:Name: Avocados
INFO:__main__:MAC Address: d0:37:45:da:d6:12
INFO:__main__:API Version: 4.6.1
INFO:__main__:Software Version: 4.0.1144
INFO:__main__:Hardware Version: 3
INFO:__main__:RAINMACHINE DIAGNOSTICS
INFO:__main__:{'hasWifi': True, 'uptime': '66 days, 23:13:14', 'uptimeSeconds': 5785994, 'memUsage': 17056, 'networkStatus': True, 'bootCompleted': True, 'lastCheckTimestamp': 1683071927, 'wizardHasRun': True, 'standaloneMode': False, 'cpuUsage': 1.0, 'lastCheck': '2023-05-02 16:58:47', 'softwareVersion': '4.0.1144', 'internetStatus': True, 'locationStatus': True, 'timeStatus': True, 'wifiMode': None, 'gatewayAddress': '192.168.0.1', 'cloudStatus': 0, 'weatherStatus': True}
INFO:__main__:RAINMACHINE PARSERS
INFO:__main__:[{'lastRun': None, 'lastKnownError': '', 'hasForecast': False, 'uid': 8, 'hasHistorical': True, 'description': 'Personal Weather Station direct data download in WeatherDisplay raw format', 'enabled': False, 'fileName': 'pws-parser.py', 'version': 1.0, 'params': {'urlPath': 'http://weather-display.com/windy/clientraw.txt', 'maxAllowedDistance': 100000}, 'isRunning': False, 'custom': False, 'name': 'WeatherDisplay Parser'}, {'lastRun': '2023-05-02 16:43:03', 'lastKnownError': '', 'hasForecast': True, 'uid': 3, 'hasHistorical': True, 'description': 'Global weather service with personal weather station access from Weather Underground', 'enabled': True, 'fileName': 'wunderground-parser.py', 'version': 1.0, 'params': {'apiKey': '09f242d766474c48b242d76647ac48d8', '_apiForecastDays': 5, 'useCustomStation': True, '_nearbyStationsIDList': ['KCAFALLB182 (0.0km; lat=33.42, lon=-117.3)', 'KCAFALLB185 (2.4km; lat=33.44, lon=-117.3)', 'KCAFALLB98 (2.4km; lat=33.44, lon=-117.3)', 'KCAFALLB186 (2.4km; lat=33.44, lon=-117.3)', 'KCAFALLB16 (2.4km; lat=33.44, lon=-117.3)', 'KCAFALLB176 (2.4km; lat=33.44, lon=-117.3)', 'KCATEMEC139 (5.3km; lat=33.47, lon=-117.3)', 'KCAFALLB191 (5.4km; lat=33.39, lon=-117.26)', 'KCAFALLB58 (5.8km; lat=33.43, lon=-117.24)', 'KCAFALLB140 (5.8km; lat=33.45, lon=-117.25)'], 'maxDistance': 20, '_airportStationsIDList': ['KNFG (14.2km; lat=33.3, lon=-117.36)'], 'customStationName': 'KCAFALLB182,KCAFALLB16,KCAFALLB186,KCAFALLB98,KCAFALLB185'}, 'isRunning': False, 'custom': False, 'name': 'WUnderground Parser'}, {'lastRun': None, 'lastKnownError': '', 'hasForecast': True, 'uid': 1, 'hasHistorical': False, 'description': 'Global weather service from https://openweathermap.org/', 'enabled': False, 'fileName': 'owm-parser.py', 'version': 1.0, 'params': {'apiKey': None}, 'isRunning': False, 'custom': False, 'name': 'OpenWeatherMap Parser'}, {'lastRun': None, 'lastKnownError': '', 'hasForecast': True, 'uid': 5, 'hasHistorical': True, 'description': 'Simulated Fake weather data for developers', 'enabled': False, 'fileName': 'simulator-parser.py', 'version': 1.0, 'params': {'maxTemp': 25, 'minTemp': 5, '_rain6qpf': [], '_lastTS': []}, 'isRunning': False, 'custom': False, 'name': 'Simulator Parser'}, {'lastRun': '2023-05-02 16:43:03', 'lastKnownError': '', 'hasForecast': True, 'uid': 12, 'hasHistorical': True, 'description': 'North America weather forecast and observations from National Oceanic and Atmospheric Administration', 'enabled': True, 'fileName': 'noaa-parser.py', 'version': 1.0, 'params': {'_recommendedDistance': 20, 'selectedStation': 'KL18', '_stations': [['SDDUZ', 8.0, 389.0], ['KL18', 9.0, 216.0], ['HP007', 11.0, 468.0], ['SRUC1', 13.0, 606.0], ['E4050', 16.0, 659.0], ['KNFG', 14.0, 23.0], ['SDTEC', 20.0, 363.0], ['PZAC1', 19.0, 139.0], ['PAUSD', 21.0, 125.0], ['KF70', 23.0, 411.0], ['E3055', 22.0, 131.0], ['CRISD', 24.0, 107.0], ['KOKB', 23.0, 9.0], ['ORTSD', 26.0, 329.0], ['E2061', 25.0, 159.0], ['ECSC1', 27.0, 833.0], ['SDFRV', 28.0, 434.0], ['E3174', 25.0, 5.0], ['SCRSD', 27.0, 251.0], ['AU709', 28.0, 470.0], ['CAPC1', 29.0, 242.0], ['CBDSD', 32.0, 22.0], ['KCRQ', 32.0, 100.0], ['VLCC1', 34.0, 452.0], ['D5683', 34.0, 178.0], ['RINSD', 35.0, 325.0], ['HP014', 37.0, 1650.0], ['HMMC1', 39.0, 780.0], ['E3236', 39.0, 183.0], ['C7445', 41.0, 405.0], ['E1292', 42.0, 467.0], ['PAMC1', 42.0, 1672.0], ['UCMO', 43.0, 579.0], ['C9939', 42.0, 655.0], ['C5283', 44.0, 296.0], ['SDPRR', 45.0, 457.0], ['MHEC1', 47.0, 462.0], ['PSQC1', 46.0, 78.0], ['E3225', 46.0, 123.0], ['OGVC1', 47.0, 848.0], ['SOBSD', 46.0, 4.0], ['WRBSD', 46.0, 227.0], ['E2652', 49.0, 210.0]], '_lastAlert': None, 'useObservations': True}, 'isRunning': False, 'custom': False, 'name': 'NOAA Parser'}, {'lastRun': None, 'lastKnownError': '', 'hasForecast': True, 'uid': 14, 'hasHistorical': True, 'description': 'A parser that only output fixed values for testing', 'enabled': False, 'fileName': 'fixed-parser.py', 'version': 1.0, 'params': {'temperatureValues': '10, 20, 30, 30, 20, 10,10, 20, 30, 30, 20, 10,10, 20, 30, 30, 20, 10,10, 20, 30, 30, 20, 10,10, 20, 30, 30, 20, 10,10, 20, 30, 30, 20, 10,10, 20, 30, 30, 20, 10', 'qpfValues': '0, 0, 0, 0, 0, 0,0, 0, 0, 0, 0, 0,0.1, 0.1, 0.1, 0.1, 0.1, 0.1,0, 0, 0, 0, 0, 0,0, 0, 0, 0, 0, 0,0.1, 0.1, 0.1, 0.1, 0.1, 0.1,0, 0, 0, 0, 0, 0', 'startTimestamp': ''}, 'isRunning': False, 'custom': False, 'name': 'Fixed Parser'}, {'lastRun': None, 'lastKnownError': '', 'hasForecast': True, 'uid': 16, 'hasHistorical': False, 'description': 'Weather data from www.accuweather.com<http://www.accuweather.com>', 'enabled': False, 'fileName': 'user-accuweather-parser.py', 'version': 1.02, 'params': {'LocationKey': None, 'ApiKey': None, 'ZipCode': None}, 'isRunning': False, 'custom': True, 'name': 'AccuWeather Network Weather Information Parser'}, {'lastRun': None, 'lastKnownError': '', 'hasForecast': False, 'uid': 7, 'hasHistorical': True, 'description': 'Weather observations from NetAtmo personal weather station', 'enabled': False, 'fileName': 'netatmo-parser.py', 'version': 1.0, 'params': {'username': '', 'useSpecifiedModules': False, '_availableModules': [], 'specificModules': '', 'password': ''}, 'isRunning': False, 'custom': False, 'name': 'Netatmo Parser'}, {'lastRun': None, 'lastKnownError': '', 'hasForecast': True, 'uid': 9, 'hasHistorical': True, 'description': 'RainMachine Weather Rules with WUnderground instant data. This feature is in early development do not enable unless you know what you are doing.', 'enabled': False, 'fileName': 'weather-rules.py', 'version': 1.0, 'params': {'apiKey': '', 'rules': '[\n                {\n                  "variable": "temperature",\n                  "operator": ">",\n                  "value": 36,\n                  "action": "log",\n                  "params": {"msg": "Temperature over 36 degrees"}\n                }\n              ]', 'stationName': '', '_observations': {}, '_actions': ['log']}, 'isRunning': False, 'custom': False, 'name': 'Weather Rules Parser'}, {'lastRun': None, 'lastKnownError': '', 'hasForecast': False, 'uid': 4, 'hasHistorical': True, 'description': 'Example parser for developers', 'enabled': False, 'fileName': 'example-parser.py', 'version': 1.0, 'isRunning': False, 'custom': False, 'name': 'My Example Parser'}, {'lastRun': None, 'lastKnownError': '', 'hasForecast': False, 'uid': 15, 'hasHistorical': True, 'description': 'Live personal weather station data from www.ambientweather.net<http://www.ambientweather.net>', 'enabled': False, 'fileName': 'user-ambientweather-parser.py', 'version': 1.01, 'params': {'macAddress': None, 'apiKey': None, 'applicationKey': None}, 'isRunning': False, 'custom': True, 'name': 'Ambient Weather Network'}, {'lastRun': None, 'lastKnownError': '', 'hasForecast': False, 'uid': 10, 'hasHistorical': True, 'description': 'Florida Automated Weather Network observations', 'enabled': False, 'fileName': 'fawn-parser.py', 'version': 1.0, 'params': {'station': 480, 'useHourly': False}, 'isRunning': False, 'custom': False, 'name': 'FAWN Parser'}, {'lastRun': None, 'lastKnownError': '', 'hasForecast': False, 'uid': 6, 'hasHistorical': True, 'description': 'California Irrigation Management Information System weather stations', 'enabled': False, 'fileName': 'cimis-parser.py', 'version': 1.0, 'params': {'appKey': 'f769ef5e-1f7b-48f2-a17b-427fe9c43e74', 'customStation': True, 'station': 62, 'historicDays': 60}, 'isRunning': False, 'custom': False, 'name': 'CIMIS Parser'}, {'lastRun': None, 'lastKnownError': '', 'hasForecast': True, 'uid': 2, 'hasHistorical': False, 'description': 'Global weather service from Norwegian Meteorological Institute http://met.no', 'enabled': False, 'fileName': 'met-no-parser.py', 'version': 1.0, 'isRunning': False, 'custom': False, 'name': 'METNO Parser'}, {'lastRun': None, 'lastKnownError': '', 'hasForecast': True, 'uid': 11, 'hasHistorical': False, 'description': 'Global weather service from https://darksky.net (forecast.io)', 'enabled': False, 'fileName': 'forecast-io-parser.py', 'version': 1.0, 'params': {'appKey': None}, 'isRunning': False, 'custom': False, 'name': 'ForecastIO Parser'}, {'lastRun': None, 'lastKnownError': '', 'hasForecast': True, 'uid': 13, 'hasHistorical': True, 'description': 'Allows weather data to be pushed to RainMachine via REST API calls', 'enabled': False, 'fileName': 'api-parser', 'version': 1.0, 'isRunning': False, 'custom': False, 'name': 'Local Weather Push Parser'}]
INFO:__main__:ALL PROGRAMS….then ending with this
INFO:__main__:FLOW METER
INFO:__main__:{'flowMeterWateringClicks': 3, 'flowMeterStartIndexClicks': 0, 'flowMeterLeakClicks': 0}
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000019FE440B0A0>
Traceback (most recent call last):
  File "C:\Users\mvawter\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Users\mvawter\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\mvawter\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 745, in call_soon
    self._check_closed()
  File "C:\Users\mvawter\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000019FE440B0A0>
Traceback (most recent call last):
  File "C:\Users\mvawter\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Users\mvawter\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\mvawter\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 745, in call_soon
    self._check_closed()
  File "C:\Users\mvawter\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed

**Comment by mvawter** [comment]
Everything runnin now.
Could you point me to how to generate a 7 day watering history for 8 zones?

**Comment by bachya** [comment]
Did you try the endpoint I suggested [above](#issuecomment-1523529750)?

**Comment by mvawter** [comment]
Thanks, I’ll try it!!!

Best wishes, Marquis P Vawter
________________________________

**Comment by mvawter** [comment]
It’s working well, thanks.
