### ISSUE TITLE
Make port optional

### ISSUE THREAD

**Issue by tfitts** [bachya/regenmaschine#9]
I have a first-gen RainMachine and the API runs on port 80 instead of 8080. Since port 8080 is hardcoded I can't use this. It would be great if port 8080 could be default and you could pass in a different port.

It also looks like first-gen machines only run on http not https so that would be another good config options.

**Comment by bachya** [comment]
Thanks for reaching out! I've got an enhancement in place that should take care of this. Even though my tests pass, I would love your help testing it against your actual unit before I merge it into the main branch:

```bash
$ git clone git@github.com:bachya/regenmaschine.git
$ cd regenmaschine
$ git fetch origin bug-9:bug-9
$ git checkout bug-9
$ pip install .
```

Give that a shot and let me know how you get on.

**Comment by tfitts** [comment]
The enhancement doesn't work.  I don't know if you saw but I edited my original issue to include that the first-gen rainmachine also uses http instead of https.  I'm pretty sure that is the only other change required.  I setup a proxy that took an https request on 8080 and forwarded it as a regular http request on port 80 of my rainmachine and the switches came up in HA fine and I was also able to turn one on.

**Comment by bachya** [comment]
@tfitts: I didn't see that edit until now; thanks for pointing it out. I need some time to consider the best way to implement this, but I'll get back to you soon.

**Comment by tfitts** [comment]
I also just edited the auth.py file and changed it to http instead of https and it worked.  Obviously it needs to support both but just wanted to let you know that should do it.

**Comment by bachya** [comment]
@tfitts: Great; glad to hear it's a fairly localized change.

**Comment by bachya** [comment]
@tfitts: Okay, wasn't bad at all to properly support both. Install the latest test version for me?

```bash
# On the bug-9 branch:
$ git fetch origin bug-9
$ git merge bug-9
$ pip install .
```

Once installed, you can specify the port when creating a LocalAuthenticator:

```python
auth = rm.Authenticator.create_local('192.168.1.100', 'password', port=80, https=False)
client = rm.Client(auth)
```

P.S., I noticed you mentioned "HA" – FYI, I'll work quickly on a PR that adds this functionality to their next release.

**Comment by tfitts** [comment]
I'm just reading over the documentation and it looks like the original actually has HTTPS supprot as well (on port 443 imagine that).

**Comment by tfitts** [comment]
the latest version with https=False also allows a connection on port 80 in case you want to roll with that option as well.

**Comment by bachya** [comment]
@tfitts: Not sure what you mean by that. Specifying `port` and `https` are disconnected from each other; seems rather Pythonic to ask forgiveness than permission with parameter combos. Am I missing something?

**Comment by tfitts** [comment]
No, they both work. I'm just saying since all the devices seem to support HTTPS you don't necessarily need to provide the option to go with HTTP but it does give people more options.

**Comment by bachya** [comment]
Ah, got it. Thank you! If we're good to go, I'll merge this in.

**Comment by tfitts** [comment]
For sure.  Thanks a ton for your work on this.  I was actually considering doing this addon myself but have had a crazy busy summer so far.  Did you catch my pull request for the stop command on gen-1 devices?  I'm not sure why it's needed.  It's not mentioned in the docs but it doesn't work without it.  I just looked at the network requests using the RainMachine frontend to figure out what it was doing.

**Comment by bachya** [comment]
@tfitts: My pleasure! I didn't catch that PR – will check it out soon. Thanks for your support and help!
